services:
  db:
    container_name: demo-mysql
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demodb
      MYSQL_USER: demouser
      MYSQL_PASSWORD: password
    networks:
      - db-network

  phpmyadmin:
    container_name: demo-phpadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - db-network

  flyway:
    container_name: demo-migrations
    image: flyway/flyway
    depends_on:
      - db
    command: -url=jdbc:mysql://db:3306/demodb -user=demouser -password=password migrate
    volumes:
      - ./db/migrations:/flyway/sql
    networks:
      - db-network

networks:
  db-network:

volumes:
  db_data:
